### PR TITLE
Added party member crosshairs and slight change in UI

### PR DESCRIPTION
**Pull request by borislav-draganov**
ADDED: Crosshairs for party members in their respective color
CHANGED: position and size of UI windows

### CODE REVIEW

**Comment by dimotsai** [comment]
@borislav-draganov Thanks a lot for implementing crosshairs for party members. I would like to separate this pull request into two part. Would you please open another pull request for UI changes? We should discuss it further.

**Comment by borislav-draganov** [comment]
Not sure I understood correctly. You want me to cancel this pull request and create two new ones - one for the crosshairs and one for the UI, is that correct? If so I'd appreciate a pointer as to how to do so (honestly, I haven't used GitHub a lot)

**Comment by dimotsai** [comment]
@borislav-draganov 
Yes, create two branches - one for the crosshairs and one for the UI. And then you create two pull requests for the respective branch.
#38

**Comment by dimotsai** [comment]
this document might help you: https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request

**Comment by borislav-draganov** [comment]
OK, I'll check it out for the UI changes. In the meantime I reverted the commit and made a pull request with only the party member crosshairs. You can look into it and see if you like it

**Pull request closed without merging**
