### PR TITLE
X&Y Axes

### PR DESCRIPTION
**Pull request by Elite01**
With an option to enable/disable. 
It seems i did something wrong with the first pull requst - sorry

### CODE REVIEW

**Comment by dimotsai** [comment]
Looks good. :+1:
I was thinking that if we could cut more small areas, will it be more easier to address where we are? Just a thought.

**Comment by Elite01** [comment]
@dimotsai
cutting the map to even smaller areas whould make communicating hard
Actually i was thinking labeling the areas would've been great.
"i am at area 1".
on a different note - what do you say about little rectangles on the map showing your field of view?

**Comment by dimotsai** [comment]
@Elite01 I'd suggest you separate this pull request into two part. Pull requests are base on git branches. Any changes on a branch will affect the respective pull request. Separate it into two branches, so we can discuss them separately.

**Comment by Elite01** [comment]
@dimotsai Done

**Pull request merged**
