### PR TITLE
X+Y Axis

### PR DESCRIPTION
**Pull request by Elite01**
Adds 2 black lines that cut the map into 4 quarters.
so communicate more easily ("I am middle-right").
just a suggestion.

### CODE REVIEW

**Comment by dimotsai** [comment]
@Elite01 Thanks. That's a good idea to separate several areas.
Would you please add an option to turn on/off these lines? Also, renaming `anonymous` to `An Unnamed Cell` should not be included into this pull request.

**Comment by Elite01** [comment]
@dimotsai the renaming was a personal thing i forgot about... sorry.
as for the on/off option - i dont know how to edit the pull requst

**Comment by dimotsai** [comment]
Push commits to the branch you created and the pull request will update
automatically.

**Comment by Elite01** [comment]
this code is problametic. made a new pull request

**Pull request closed without merging**
